#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=30:00:00
#PBS -N NgsMap
#PBS -M klc328@nyu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

# Call with qsub -t ${NUM_INDIVIDUALS} call_make.pbs

working_dir=$PBS_O_WORKDIR

module load jdk/1.8.0
module load bamtools/intel/2.3.0

# This points to VcfStats.pm
export PERL5LIB=$PERL5LIB:${HOME}/downloads/vcftools-0.1.14/src/perl

# ------------------------------------------------------------------------------
# Run pipeline
# ------------------------------------------------------------------------------

cd $working_dir

THIS_IND=`awk "NR==$PBS_ARRAYID" data/individual_list.txt`

echo "Starting Make for individual $THIS_IND";

# To just test:
# make --just-print -s -f full_analysis.mk indiv IND_ID=${THIS_IND}

make -s -f full_analysis.mk indiv IND_ID=${THIS_IND}

echo "Finished Make";

exit;